services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    App\Domain\Port\PhotoReadRepositoryInterface: '@App\Infrastructure\Persistence\DoctrinePhotoRepository'
    App\Domain\Port\LikeRepositoryInterface: '@App\Infrastructure\Persistence\DoctrineLikeRepository'
    App\Domain\Port\UserReadRepositoryInterface: '@App\Infrastructure\Persistence\DoctrineUserReadRepository'
    App\Domain\Port\PhotoFindRepositoryInterface: '@App\Infrastructure\Persistence\DoctrinePhotoRepository'
    App\Domain\Port\AuthTokenReadRepositoryInterface: '@App\Infrastructure\Persistence\DoctrineAuthTokenReadRepository'
