services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Infrastructure\ExternalApi\Mock\PhoenixApiMock:
        public: true

    App\Domain\Port\PhoenixApiClientInterface: '@App\Infrastructure\ExternalApi\Mock\PhoenixApiMock'
